-- APPLIED LIVE 2026-08-17 via Supabase MCP (recorded server-side as
-- draft_clock_server_side + season_readiness_game_rules +
-- token_awards_next_week_both_finalize_paths).
--
-- Structural change:
ALTER TABLE uff_leagues ADD COLUMN IF NOT EXISTS draft_started_at timestamptz;

-- Function changes (full final bodies live in ../schema-snapshot/functions.sql,
-- the disaster-recovery source of truth for ALL game-logic RPCs):
--   start_draft                  — stamps draft_started_at = now() on start
--   force_autopick (NEW)         — any member executes the overdue pick once
--                                  last-pick picked_at (+30s round buffer on
--                                  round-first picks, +clock, +15s grace) has
--                                  passed; queue-top else best-ADP; mirrors
--                                  make_draft_pick's insert core (audit U6)
--   move_to_ir                   — accepts official IR OR injury_status
--                                  IR/Out/Doubtful/PUP (was IR-only; UI showed
--                                  the button for Out/Doubtful → error clicks)
--   award_season_titles          — bracket-driven champion with completion
--                                  guard (was: any completed playoff week could
--                                  crown a semifinalist by points heuristic)
--   finalize_week                — parity with cron path: marks tokens used,
--                                  awards faction-war tokens
--   finalize_all_active_leagues  — token awards now land on week N+1 (were
--                                  written to the just-finalized week, where
--                                  the roster page never reads them)
